did some change

diff --git a/Downloads/api-testing-with-mocha-chai-master/.husky/pre-commit b/Downloads/api-testing-with-mocha-chai-master/.husky/pre-commit
--- a/Downloads/api-testing-with-mocha-chai-master/.husky/pre-commit
+++ b/Downloads/api-testing-with-mocha-chai-master/.husky/pre-commit
@@ -1,1 +1,18 @@
+#!/bin/bash
+
+# Run npm test command
+echo "Running npm test..."
 npm test
+
+if [ $? -ne 0 ]; then
+    echo "Tests failed. Aborting commit."
+    exit 1
+else
+    echo "Tests passed. Committing changes..."
+    exit 0
+fi
+#
+#
+#
+#
+#
